//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compiler.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RuntimeMessagesError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RuntimeMessagesError() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Compiler.Core.RuntimeMessagesError", typeof(RuntimeMessagesError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation division by zero..
        /// </summary>
        public static string DivByZero {
            get {
                return ResourceManager.GetString("DivByZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not plus string with int..
        /// </summary>
        public static string intStringPluse {
            get {
                return ResourceManager.GetString("intStringPluse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not valid for the Unary operataor {1} ..
        /// </summary>
        public static string InvalideType {
            get {
                return ResourceManager.GetString("InvalideType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not found main method..
        /// </summary>
        public static string NoMain {
            get {
                return ResourceManager.GetString("NoMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function without returnn statment..
        /// </summary>
        public static string NoReturnInFunction {
            get {
                return ResourceManager.GetString("NoReturnInFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is not valid..
        /// </summary>
        public static string NotValid {
            get {
                return ResourceManager.GetString("NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when read object file..
        /// </summary>
        public static string ObjFile {
            get {
                return ResourceManager.GetString("ObjFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The procedure can not contain return statment..
        /// </summary>
        public static string ReturnInProcedure {
            get {
                return ResourceManager.GetString("ReturnInProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number is too big so it can not contained in Int..
        /// </summary>
        public static string ToBigOnInt {
            get {
                return ResourceManager.GetString("ToBigOnInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of Unassigend variable..
        /// </summary>
        public static string UnassigedVariable {
            get {
                return ResourceManager.GetString("UnassigedVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnCompitable types for {0} statment..
        /// </summary>
        public static string Uncompiable {
            get {
                return ResourceManager.GetString("Uncompiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not Execute Instruction..
        /// </summary>
        public static string UnknownInstruction {
            get {
                return ResourceManager.GetString("UnknownInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the only types {0} with the operators {1}..
        /// </summary>
        public static string ValidType {
            get {
                return ResourceManager.GetString("ValidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of {0} variables in call is different from number of {0} vairables in Definetion..
        /// </summary>
        public static string VarsDifferents {
            get {
                return ResourceManager.GetString("VarsDifferents", resourceCulture);
            }
        }
    }
}
