//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compiler.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SyntaxMessagesError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SyntaxMessagesError() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Compiler.Core.SyntaxMessagesError", typeof(SyntaxMessagesError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not use &apos;Call&apos; Keyword with function , use &apos;Call&apos; Keyword with procedure only..
        /// </summary>
        public static string CallFunction {
            get {
                return ResourceManager.GetString("CallFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name {0} is Defined more than once..
        /// </summary>
        public static string DuplicateDefination {
            get {
                return ResourceManager.GetString("DuplicateDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are missing Expression here. between the {0} and {1}..
        /// </summary>
        public static string ExpMiss {
            get {
                return ResourceManager.GetString("ExpMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file that included in the project is not exist..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statments must not exist outside the methods (functions or procedures)..
        /// </summary>
        public static string InsideMethod {
            get {
                return ResourceManager.GetString("InsideMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tokne {0} is not valid here..
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &quot;{0}&quot; is called somewhere and not defined..
        /// </summary>
        public static string MethodNotDefined {
            get {
                return ResourceManager.GetString("MethodNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main file &quot;{0}&quot; Does not contain Main Procedure or Function..
        /// </summary>
        public static string NoMainMethod {
            get {
                return ResourceManager.GetString("NoMainMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This statment will does nothing..
        /// </summary>
        public static string NoOperation {
            get {
                return ResourceManager.GetString("NoOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method call is not as method definition..
        /// </summary>
        public static string NotAsCalled {
            get {
                return ResourceManager.GetString("NotAsCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SemiColon must be at the end of the statment but not found..
        /// </summary>
        public static string SemiColon {
            get {
                return ResourceManager.GetString("SemiColon", resourceCulture);
            }
        }
    }
}
