//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compiler.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WordMessagesError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WordMessagesError() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Compiler.Core.WordMessagesError", typeof(WordMessagesError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Comments allowed after the macro end in the same line..
        /// </summary>
        public static string CommentsAfterMacro {
            get {
                return ResourceManager.GetString("CommentsAfterMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Constant &apos;number of string&apos; is not valid..
        /// </summary>
        public static string ConstantNotValid {
            get {
                return ResourceManager.GetString("ConstantNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of string is not found in the same line that begin.
        /// </summary>
        public static string EndString {
            get {
                return ResourceManager.GetString("EndString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecogized escape sequence.
        /// </summary>
        public static string EscapeSequence {
            get {
                return ResourceManager.GetString("EscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the file &quot;{0}&quot; is Empty..
        /// </summary>
        public static string FileEmpty {
            get {
                return ResourceManager.GetString("FileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit or a, b , c ,d ,e ,f is Expected after 0x but not found..
        /// </summary>
        public static string HexaDeciaml {
            get {
                return ResourceManager.GetString("HexaDeciaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Identifier is known, vaiables in define statment must be used for the first time..
        /// </summary>
        public static string IdKnown {
            get {
                return ResourceManager.GetString("IdKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the file &quot;{0}&quot; has no code, it is all comments..
        /// </summary>
        public static string LackFileCode {
            get {
                return ResourceManager.GetString("LackFileCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read two macros or more in the same line, Please sperate each macro in sperated line..
        /// </summary>
        public static string MacrosInSameLine {
            get {
                return ResourceManager.GetString("MacrosInSameLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After &apos;#&apos; must not come any space, include or define must come immediatly after &apos;#&apos;..
        /// </summary>
        public static string NoSpace {
            get {
                return ResourceManager.GetString("NoSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Excpected but not found..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Char is not valid..
        /// </summary>
        public static string NotValidChar {
            get {
                return ResourceManager.GetString("NotValidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number is to long, it could not contained in double variable..
        /// </summary>
        public static string OverFlow {
            get {
                return ResourceManager.GetString("OverFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single point is found wihtout any digit..
        /// </summary>
        public static string SinglePoint {
            get {
                return ResourceManager.GetString("SinglePoint", resourceCulture);
            }
        }
    }
}
